server:
  port: 8100

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.32.169:3306/user_center?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 15151112063Gw
    # HikariCP 连接池配置
    hikari:
      minimum-idle: 2              # 开发环境调小，减少资源占用
      maximum-pool-size: 10        # 开发环境够用了
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 60000        # 加上这行，主动保活，避免连接被防火墙断掉
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        ip: 47.122.87.219 # 此处填写user-service部署在哪个服务器的ip
        server-addr: 47.122.87.219:8848 # nacos服务地址
        namespace: 7e1f4523-af8b-48ab-9ec2-368a30db92ee # nacos命名空间id
        group: DEFAULT_GROUP  # 分组名称
        cluster-name: NJ      # nacos集群名称
    stream:
      function:
        definition: addBonus
      rocketmq:
        binder:
          name-server: 124.223.32.169:9876
      bindings:
        addBonus-in-0:
          destination: add-bonus-topic
          group: consumer-group-add-bonus
          content-type: application/json
#          consumer:
#            auto-startup: false   # ① 先不自动启动消费者


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.userservice.dto

# RocketMQ 配置
#rocketmq:
#  #RocketMQ NameServer 地址
#  name-server: 124.223.32.169:9876

jwt:
  secret: suibianxie
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600



