server:
  port: 8100

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        ip: 47.122.87.219 # 此处填写user-service部署在哪个服务器的ip
        server-addr: 47.122.87.219:8848 # nacos服务地址
        namespace: 7e1f4523-af8b-48ab-9ec2-368a30db92ee # nacos命名空间id
        group: DEFAULT_GROUP  # 分组名称
        cluster-name: NJ      # nacos集群名称






